name: Traceability Matrix

on:
  push:
  pull_request:

jobs:
  rtm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout requirements
        uses: actions/checkout@v3

      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/haski-frontend
          path: frontend

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test:report || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate traceability matrix
        run: python traceability/build.py --config traceability/config.yaml

      - name: Upload traceability matrix
        uses: actions/upload-artifact@v3
        with:
          name: rtm
          path: traceability/RTM.csv
