name: Traceability --> GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write       # für deploy-pages
  id-token: write    # für OIDC

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  rtm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout requirements
        uses: actions/checkout@v4

      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/haski-frontend
          path: frontend

      - name: Prepare npm cache directory
        run: mkdir -p ~/.npm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install frontend dependencies
        working-directory: frontend
        run: yarn install

      - name: Run frontend tests (JSON/JUnit Report)
        working-directory: frontend
        run: yarn test:report || true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python deps (traceability tool)
        run: pip install -r requirements.txt

      - name: Generate traceability matrix
        run: python traceability/build.py --config traceability/config.yaml

      # --- GitHub Pages Site bauen ---
      - name: Build Pages site
        run: |
          rm -rf site && mkdir -p site/rtm
          cp traceability/RTM.csv site/rtm/RTM.csv
          cat > site/index.md << 'EOF'
          # HASKI Traceability

          - **Traceability-Matrix (CSV):** [Download](./rtm/RTM.csv)

          _(Automatisch generiert. Stand: $GITHUB_SHA)_
          EOF

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: rtm
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
